### PR TITLE
Fix profile navigation

### LINKED ISSUE #474: Clicking on a user profile leads to error message
**Describe the bug**
Clicking on a user profile icon or name from any page on DevHub leads to an error message.

**To Reproduce**
1. Go to the [activity feed](https://near.social/devhub.near/widget/app?page=feed)
2. Click on a user's profile image or name or user name
3. See `Source code for "devhub.near/widget/devhub.near/widget/ProfilePage" is not found` error message

**Expected behavior**
Clicking on a user's image should lead to their profile page.

**Screenshots**
Image

**Desktop (please complete the following information):**
 - OS: iOS
 - Browsers: Chrome & Safari
 - Version: Latest

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolved #474

### CODE REVIEW

File: src/devhub/components/molecule/ProfileCard.jsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ const ProfileCard = (props) => {
       href={
         link !== true
           ? link
-          : `${REPL_DEVHUB}/widget/ProfilePage?accountId=${accountId}`
+          : `#/${REPL_MOB}/widget/ProfilePage?accountId=${accountId}`
```
Comment (elliotBraem) [inline src/devhub/components/molecule/ProfileCard.jsx:67]: I think we could remove the #
