### PR TITLE
Ft: Autocomplete widget added

### LINKED ISSUE #200: Tagging/mentions doesn't work if you do not follow anyone
**Describe the bug**
When an account doesn't follow anyone, you cannot use the tagging/mentions feature.

**To Reproduce**
1. A user that doesn't follow anyone should create a new idea/solution or try to reply to any post.
2. Type @t in the description.
3. The user does not see any suggested users.
Screenshot 2023-07-11 at 5 41 36 PM

**Expected behavior**
User should see suggested user names:
Screenshot 2023-07-11 at 5 43 12 PM

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 114.0.5735.198 (

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #200

### CODE REVIEW

File: src/devhub/components/molecule/AccountAutocomplete.jsx [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+  if (accountIdSearchIndex > -1 || nameSearchIndex > -1) {
+    score += 10;
+
+    if (accountIdSearchIndex === 0) {
+      score += 10;
+    }
+    if (nameSearchIndex === 0) {
+      score += 10;
+    }
+    if (followingData[accountId] === "") {
```
Comment (ailisp) [inline src/devhub/components/molecule/AccountAutocomplete.jsx:33]: Did you test it with an account without following data? Just want to ensure followingData is not `undefined` or `null`, otherwise this line would error

Comment (Megha-Dev-19) [reply src/devhub/components/molecule/AccountAutocomplete.jsx:33]: Yes I checked it for null
I will add a preview link for you test it
https://near.org/megha19.near/widget/app?page=create

**Review by ailisp — APPROVED** [review]
Works great for account without following. Thank you! If you have additional time consider to submit PR to NearSocial to help them fix this issue as well!

**Comment by Megha-Dev-19** [comment]
@frol here is the [link](https://github.com/near/near-discovery-components/pull/559)
